sudo: required
dist: trusty

language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

install:
  - sh -c "sudo apt-get -y install uuid-dev libgearman-dev gearman gearman-job-server"
before_script:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then curl -L -o gearman.tgz http://pecl.php.net/get/gearman/1.1.2; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then curl -L -o gearman.tgz https://github.com/wcgallego/pecl-gearman/archive/gearman-2.0.1.tar.gz; fi;
  - tar -xzf gearman.tgz
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then sh -c "cd gearman-1.1.2 && phpize && ./configure && make && sudo make install && cd .."; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then sh -c "cd pecl-gearman-gearman-2.0.1 && phpize && ./configure && make && sudo make install && cd .."; fi;
  - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email: false
